name: Deploy to GCP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
           cd /home/ubuntu/iminhas.com-site
            git pull origin main
            sudo cp -r src/index.html /var/www/html/index.html
            sudo cp -r src/css/style.css /var/www/html/css/style.css
           sudo cp -r src/assets/ /var/www/html/assets/
           echo "✅ Deployment complete!"
